### PR TITLE
Error in the bare metal build process:no acceptable C compiler found in $PATH  && CMAKE_CXX_COMPILER-NOTFOUND was not found

### PR DESCRIPTION
**Pull request by ThinkBlue1991**
os: `centos 7.6.1810` 最小化安装
执行`./build.sh`时分别报错：
```
configure: error: in `/root/PolarDB-for-PostgreSQL':
configure: error: no acceptable C compiler found in $PATH
See `config.log' for more details
```
&&
```
CMake Error: your CXX compiler: "CMAKE_CXX_COMPILER-NOTFOUND" was not found.   Please set CMAKE_CXX_COMPILER to a valid compiler path or name.
```
IMO：这应该是缺少C和C++的编译环境，需要安装`gcc gcc-c++`

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
I think this operation will damage our local GCC environment. The hypothesis of bare metal is dangerous! The change is not recommended.

**Comment by ThinkBlue1991** [comment]
IMO，if our local has GCC environment, The installation operation should not be successful,So the change will not affect the local environment.

**Comment by mingzong-sdm** [comment]
We will provide a docker version in the near future, please continue to pay attention

**Comment by ThinkBlue1991** [comment]
可以使用docker版本，Closed！

**Pull request closed without merging**
