### PR TITLE
参考sql server 更新统计信息算法(https://learn.microsoft.com/en-us/sql/relational-databases/statistics/statistics?view=sql-server-ver16),更新触发算法

### PR DESCRIPTION
**Pull request by qiuwenhuifx**
参考sql server 更新统计信息算法(https://learn.microsoft.com/en-us/sql/relational-databases/statistics/statistics?view=sql-server-ver16),更新触发算法

### CODE REVIEW

**Comment by mrdrivingduck** [comment]
@qiuwenhuifx hi, seems that your are trying to PR to a wrong branch. This PR is not mergeable.

**Comment by mrdrivingduck** [comment]
@qiuwenhuifx closed due to not mergable.

**Comment by qiuwenhuifx** [comment]
@mrdrivingduck ,which branch correct ?

**Comment by mrdrivingduck** [comment]
> @mrdrivingduck ,which branch correct ?

Hi @qiuwenhuifx, you should raise PR to `POLARDB_15_STABLE` instead of `master`.

**Pull request closed without merging**
