### PR TITLE
pfs+curve sdk document

### PR DESCRIPTION
**Pull request by Cyber-SiKu**
Signed-off-by: Cyber-SiKu <Cyber-SiKu@outlook.com>

### CODE REVIEW

**Comment by mrdrivingduck** [comment]
@Cyber-SiKu This commit should be merged into `POLARDB_11_DEV`. Also, a conflict should be resolved.

**Comment by Cyber-SiKu** [comment]
> @Cyber-SiKu This commit should be merged into `POLARDB_11_DEV`. Also, a conflict should be resolved.

ok

**Comment by mrdrivingduck** [comment]
@Cyber-SiKu 4 more configuration files should also be updated, or else the page cannot be indexed. See the example [here](https://github.com/ApsaraDB/PolarDB-for-PostgreSQL/commit/2aecf70d22739647bccdcd6023393903c9613699).

**Comment by Cyber-SiKu** [comment]
> 4 more configuration files should also be updated, or else the page cannot be indexed. See the example

fix

**Pull request merged**
