### PR TITLE
OSPP: NUMA support

### PR DESCRIPTION
**Pull request by xRay2016**
Support NUMA awareness for PolarDB-for-PG.

This pull request is for [OSPP2023](https://summer-ospp.ac.cn/#/org/prodetail/2209e0088).

### CODE REVIEW

**Comment by Jiwenguan** [comment]
您好，您的邮件我已收到，愿您身体健康，万事如意！

**Comment by xRay2016** [comment]
It seems that the github workflow needs the docker images. The commit needs extral library `libnuma`, how to add this dependence?

**Comment by mrdrivingduck** [comment]
@xRay2016 Welcome. Try to update the Dockerfile [here](https://github.com/mrdrivingduck/polardb-pg-docker-images)?

**Comment by xRay2016** [comment]
> @xRay2016 Welcome. Try to update the Dockerfile [here](https://github.com/mrdrivingduck/polardb-pg-docker-images)?

OK! I will update the Dockerfile at first.

**Comment by xRay2016** [comment]
I will make the PR to numa branch first, so I close this PR.

**Pull request closed without merging**
